### ISSUE TITLE
Hyperparameter Settings

### ISSUE THREAD

**Issue by umsimonchen** [tanatosuu/sgfcf#1]
Hi. Thank you for your contribution. I am so inspired by your work SGFCF.

I am just wondering if you could share your experience with choosing the hyperparameter specifically since it seems that there are quite a lot of hyperparameters (e.g., alpha, beta, epsilon, gamma) and they vary from different datasets. 

As reported in the paper, the tuning for hyperparameters seems to require a huge cost to try out enormous values. And it will be troublesome if we try to run it on another new dataset.

Please give some insights on the hyperparameter settings. I'd appreciate it if you could give us a hand :D

Best.

**Comment by tanatosuu** [comment]
Thanks for your interest in our work. I do agree with you that the hyperparameter tuning is troublesome. Here are some rules of thumbs which I hope can help you.

To be honest, the improvement from IGF design is not that significant so you can first focus on sgfcf_wo_igf.py first. You can fix the hyperparameters first with the initialization such as:

--density='sparse' --k=100 --beta=3.0 --alpha=2.3 or --eps=0.4 --gamma=0.05
--density='dense' --k=400 --beta=1.0 --alpha=10 or --eps=0.3 --gamma=1.0

Overall, the hyperparameters are more sensitive on the sparse setting. If you use a normal 80% for training set and your data is not extremely sparse, you can stick to the dense initialization. Two principles are:
(1)	You only tune one parameter at once and fix others.
(2)	choose a large scale in the first place and then gradually reduce the scale. For instance, for the number of the features –k, you can change with a step 100 and then reduce it to 50 and to 10.
	
**--k** and (**--alpha, --eps**) are parameters significantly impact the performance, you can start with the two and then tune others. **–-alpha and –eps have the same effect, you tune either one at once** and choose the one with better performance. Lastly, for IGF, you gradually reduce \beta_1 < beta and increase \beta_2>\beta.

It might be annoying that you need to test dozens of times for tuning, but fortunately, each training only costs you a few seconds, so it won’t take you too much time for the parameter tunning.  Please do not hesitate to contact me if you have any questions or difficulty implementing our models via github or Email

**Comment by umsimonchen** [comment]
Much thanks for your kind reply. I'll try it ASAP.
